name: Standalone CLI

on: [push, pull_request]

jobs:
  machineStandalone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      
      - name: Create results directory
        run: mkdir -p scan-results
      
      - name: Run Fluidattacks scan
        run: docker run --rm -v ${PWD}:/work -w /work fluidattacks/cli:latest skims scan ./config.yml | tee scan-results/scan-output.txt
      
      - name: Generate summary report
        run: |
          echo "Scan completed at $(date)" > scan-results/summary.txt
          echo "Repository: ${{ github.repository }}" >> scan-results/summary.txt
          echo "Commit: ${{ github.sha }}" >> scan-results/summary.txt
          
      - name: Upload scan results
        uses: actions/upload-artifact@v4
        if: always()  # Upload artifacts even if the scan fails
        with:
          name: security-scan-results
          path: scan-results/
          retention-days: 30